### ISSUE TITLE
publish the lib as an autonomous package on pipy and conda

### ISSUE THREAD

**Issue by 12rambau** [loicdtx/pygadm#2]
I contacted you some time ago on LinkedIn to make modifications on the lib. As mention in my messages, I faced the issue of using GADM data recently and I would like to offer my help to make this repository more scalable. here is a small list of the modifications I would like to make in order to achieve this goal: 

- [ ] add a standalone documentation page (publish on readTheDoc, it's free, it's nicen nothing to complain about) 
- [ ] add some tests to check if the lib is compatible with multiple Python version and maybe GADM versions (4th is around the corner) 
- [ ] release the package using github actions whith SemVer and maybe some small linting rules

If you are intersted I'll open specific issues and PR for each points

**Comment by loicdtx** [comment]
Sounds good, also consider:
- [ ] licencing issues (there's one specified in setup.py but I did not especially put much thoughts into it so might be worth thinjing it through)
- [ ] If I remember correctly last time I tried there was a fiona deprecation warning about the way `vsi` was being used. Not very alarming but would need to be adressed before an eventual pypi release

**Comment by 12rambau** [comment]
Sure I'll start by setting up tests and a 1 pager documentation first to see if anything is causing issues
