### ISSUE TITLE
deprecate the need for level specification

### ISSUE THREAD

**Issue by 12rambau** [loicdtx/pygadm#4]
I coded a version of this script that does not require to specify the level of the administrative layer. 
to implement it I simply need to produce a csv of all the available admin lumber/name and find the appropriate one. 

It would require to implement a script to generate the csv in question and it would be created on installation. alternatively it could be generated by a realease script and included in the distrib.

**Comment by loicdtx** [comment]
Could you explain why you would not use the `level` argument? I do use it and find it pretty useful

**Comment by 12rambau** [comment]
Because I didn't read your code carefully ;-)
I'll create another issue with a more specific use case where I think it could make sense to adapt how the level is used.
